micronaut:
  application:
    name: purchase
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
    entity-scan:
      packages:
        - com.example.ddd.purchase

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3
